### ISSUE TITLE
Disconnected network is not reverted before the next experiment

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/zeebe-chaos#51]
A follower-restart experiment failed because the node receiving the request cannot communicate to the leader of partition 3.
zeebe-0 was receiving `CreateWorkflowInstanceRequest`. Zeebe-4 was the leader of partition 3. In the zeebe logs saw the following:
```
java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: No route to host: zeebe-4.zeebe-broker-service.1e9a4a6c-5988-4087-905d-7a54b34bd11d-zeebe.svc.cluster.local/10.56.5.26:26502`
```
So no workflow is created on partition 3. The chaos tests is waiting until a workflow is created in partition 3.

Further inspection shows the following:
```
>> kubectl exec zeebe-4  -- ip route
default via 10.56.5.1 dev eth0 
10.56.5.0/24 via 10.56.5.1 dev eth0 src 10.56.5.26 
10.56.5.1 dev eth0 scope link src 10.56.5.26 
unreachable 10.56.19.4 
>>  kubectl exec zeebe-0  -- ip route
default via 10.56.19.1 dev eth0 
unreachable 10.56.5.26 
10.56.19.0/24 via 10.56.19.1 dev eth0 src 10.56.19.5 
10.56.19.1 dev eth0 scope link src 10.56.19.5 
```

It seems the previous disconnect was not reverted.

What happened is actually the following:
1. zeebe-0 and zeebe-4 is determined as leaders of the partitions that should be disconnected from each other
2. zeebe-0 pod is restarted (node preemption, not part of the experiment)
3. A new leader is elected (zeebe-2)
4. zeebe-0 and zeebe-4 are disconnected
5. experiment ended
6. zeebe-2 and zeebe-4 is determined as leaders of the partition to be re-connected
7. zeebe-2 and zeebe-4 re-connected
8. zeebe-0 and zeebe-4 remains disconnected.
9. The next experiment starts with this broken state.

**Comment by Zelldon** [comment]
Should be fixed by https://github.com/zeebe-io/zeebe-chaos/commit/4fa21ee216d835163608983de899cf384f92f82d

Previous the created ip route was not deleted, since the 'command ip' check was also not tested in the pod more on the machine where the experiment was running. Furthermore it was problematic if a leader change happened since we only tried to reset for the current leader for the partitions. We now try to remove the ip route on all nodes if ip is installed. This is much faster then restart all pods.
